python:
    - 3.9
    - 3.10
    - 3.11
    - 3.12
    - 3.13
    - 3.14
c_compiler:
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
cxx_compiler:
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
    - vs2022 # [win]
zip_keys:
    - python
    - c_compiler # [win]
    - cxx_compiler # [win]
