name: "Build Conda Packages"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: conda build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    env:
      MY_CONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      MY_CONDA_CHANNEL: "paulscherrerinstitute"
      MY_CONDA_CMD: "conda"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: false
          auto-activate-base: true
          activate-environment: ""
      - name: Dump environments
        run: |
            printenv
            mkdir packages
            conda info
      - name: Setup docker on Linux
        if: runner.os == 'Linux'
        run: |
            ./start_docker.sh $(pwd)/packages
            echo "MY_CONDA_CMD=./conda_in_docker.sh" >> $GITHUB_ENV
      - name: Conda build environment
        run: |
            ${MY_CONDA_CMD} install conda-build anaconda-client
            ${MY_CONDA_CMD} info
      - name: Build ${{ runner.os }} packages
        run: |
            [[ -z "$MY_CONDA_TOKEN" ]] || ${MY_CONDA_CMD} config --set anaconda_upload yes
            [[ -n "$MY_CONDA_TOKEN" ]] || MY_CONDA_TOKEN=placeholder
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing epics-base || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing cachannel || true
            ${MY_CONDA_CMD} build -c $MY_CONDA_CHANNEL --token $MY_CONDA_TOKEN --skip-existing pcaspy || true
      - name: Build pure python packages
        run: |
            printf "Nothing to build\n"
        if: runner.os == 'Linux'
      - name: Stop docker
        if: runner.os == 'Linux'
        run: |
            ./stop_docker.sh
